spring:
  rabbitmq:
    host: 192.168.8.132
    username: root
    password: root
  profiles:
    active: commons,rabbitmq,mail

dubbo:
  application:
    name: ego-receive
  registry:
    address: zookeeper://192.168.8.128:2181

