dubbo:
  application:
    name: ego-trade
  registry:
    address: zookeeper://192.168.8.128:2181

server:
  port: 8086
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: commons,redis,rabbitmq


